### ISSUE TITLE
Getting urllib2.HTTPError: HTTP Error 410: Gone

### ISSUE THREAD

**Issue by anaklupa** [smartsheet-platform/samples#7]
I used the samples.

**Comment by anaklupa** [comment]
Traceback (most recent call last):
  File "test2.py", line 66, in <module>
    createSheet = Call._raw_request('/sheets', header, sheet) # Create sheet
  File "test2.py", line 48, in _raw_request
    self.resp = urllib2.urlopen(req).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 410: Gone
